# Generated by Django 3.1 on 2020-11-27 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('boards', '0001_initial'), ('boards', '0002_auto_20201122_2120')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', error_messages={}, max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(db_column='description', error_messages={}, max_length=500, verbose_name='description')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
                'db_table': 'board',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='subject', error_messages={}, max_length=50, unique=True, verbose_name='subject')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='last_updated', error_messages={})),
                ('board', models.ForeignKey(db_column='board', error_messages={}, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='boards.board')),
                ('starter', models.ForeignKey(db_column='user', error_messages={}, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to=settings.AUTH_USER_MODEL)),
                ('views', models.PositiveIntegerField(db_column='views', default=0, error_messages={}, verbose_name='views')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'db_table': 'topic',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message', error_messages={}, max_length=100, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', error_messages={})),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', error_messages={}, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', error_messages={}, on_delete=django.db.models.deletion.CASCADE, related_name='posts_created_by', related_query_name='post', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(db_column='topic', error_messages={}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='boards.topic', verbose_name='topic')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', error_messages={}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_updated_by', related_query_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
    ]
