# Generated by Django 3.1 on 2020-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(db_column='views', default=0, error_messages={}, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(db_column='message', error_messages={}, max_length=100, verbose_name='message'),
        ),
    ]
